/**
 * This file is part of the lottery core functionality.
 * 
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Any changes to this file may cause unexpected behavior.
 * Please consult the project maintainers before making modifications.
*/

import React, { createContext, useContext } from 'react';

export const BackupContext = createContext();

export default function BackupProvider({ children }) {
    return (
        <BackupContext.Provider>
            {children}
        </BackupContext.Provider>
    )
}

export const useBackup = () => {
    const context = useContext(NotificationsContext);
    if (!context) {
        throw new Error("useBackup must be used within a BackupProvider");
    }
    return context;
};