/**
 * This file is part of the BlockLotto core functionality.
 * 
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Any changes to this file may cause unexpected behavior.
 * Please consult the project maintainers before making modifications.
*/

import React, { createContext, useContext } from 'react';

export const CashoutContext = createContext();

export default function CashoutProvider({ children }) {
    return (
        <CashoutContext.Provider>
            {children}
        </CashoutContext.Provider>
    )
}

export const useCashout = () => {
    const context = useContext(NotificationsContext);
    if (!context) {
        throw new Error("useCashout must be used within a CashoutProvider");
    }
    return context;
};