/**
 * This file is part of the lottery core functionality.
 * 
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Any changes to this file may cause unexpected behavior.
 * Please consult the project maintainers before making modifications.
*/

import React, { createContext, useContext } from 'react';

export const SelectContext = createContext();

export default function SelectProvider({ children }) {
    return (
        <SelectContext.Provider>
            {children}
        </SelectContext.Provider>
    )
}

export const useSelect = () => {
    const context = useContext(NotificationsContext);
    if (!context) {
        throw new Error("useSelect must be used within a SelectProvider");
    }
    return context;
};