/**
 * This file is part of the lottery core functionality.
 * 
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Any changes to this file may cause unexpected behavior.
 * Please consult the project maintainers before making modifications.
*/

import React, { createContext, useContext } from 'react';

export const WaitingRoomContext = createContext();

export default function WaitingRoomProvider({ children }) {
    return (
        <WaitingRoomContext.Provider>
            {children}
        </WaitingRoomContext.Provider>
    )
}

export const useWaitingRoom = () => {
    const context = useContext(NotificationsContext);
    if (!context) {
        throw new Error("useWaitingRoom must be used within a WaitingRoomProvider");
    }
    return context;
};