/**
 * This file is part of the BlockLotto core functionality.
 * 
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Any changes to this file may cause unexpected behavior.
 * Please consult the project maintainers before making modifications.
*/

const rawNationalityOptions = [
    "Country A", "Country B", "Country C", "Country D"
]

export const nationalityOptions = rawNationalityOptions.map(country => {
    return {
        label: country, 
        value: country
    }
})

const rawResidencyOptions = [
    "Country A", "Country B", "Country C", "Country D"
]

export const residencyOptions = rawResidencyOptions.map(country => {
    return {
        label: country, 
        value: country
    }
})