/**
 * This file is part of the lottery core functionality.
 * 
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Any changes to this file may cause unexpected behavior.
 * Please consult the project maintainers before making modifications.
*/

const sleep = (ms) => {
    return new Promise(resolve => setTimeout(resolve, ms));
};

export default sleep;