/**
 * This file is part of the BlockLotto core functionality.
 * 
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Any changes to this file may cause unexpected behavior.
 * Please consult the project maintainers before making modifications.
*/

export const sandboxTokenInfo = {
	"tokenId": "cd5e8959e563f845c0b3d68890f960aad71e7fc96a205daaf86f28a7d3a49767",
	"ticker": "BLCs",
	"name": "Blockchain Lottery Credit (sandbox)",
	"uri": "https://lotto.mp",
	"hash": "0000000000000000000000000000000000000000000000000000000000000000",
	"decimals": 2,
	"version": 2,
	"vaultScriptHash": "92e113b144b5cafee0397426624532e4d220275a"
}