/**
 * This file is part of the BlockLotto core functionality.
 * 
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Any changes to this file may cause unexpected behavior.
 * Please consult the project maintainers before making modifications.
*/

import React from 'react';
import styled from 'styled-components';
import { CheckCircleOutlined, CloseCircleOutlined, ExclamationCircleOutlined } from '@ant-design/icons';

export default function DefaultNotification({ type, message }) {

    const Notification = styled.div`
        padding: 18px  24px;
        color: white;
        border-radius: 10px;
        display: flex;
        align-items: center;
        justify-content: center;
        gap: 10px;
        background-color: ${() => {
            switch (type) {
                case 'error':
                    return 'red';
                case 'success':
                    return 'green';
                case 'info':
                    return 'blue';
                default:
                    return 'black';
            }
        }}
    `;

    return (
        <Notification>
            {type === "success" && <CheckCircleOutlined />}
            {type === "error" && <CloseCircleOutlined />}
            {type === "info" && <ExclamationCircleOutlined />}
            {message}
        </Notification>
    )
}
