/**
 * This file is part of the lottery core functionality.
 * 
 * DO NOT EDIT THIS FILE DIRECTLY.
 * Any changes to this file may cause unexpected behavior.
 * Please consult the project maintainers before making modifications.
*/

import React, { useEffect, useState } from 'react';
import styled, { css } from 'styled-components';
import { currency } from '@core/utils/ticker';

const SlideInAnimation = css`
    @keyframes slide-in-from-top {
        0% {
            transform: translateY(-100px);
            opacity: 0;
        }
        100% {
            transform: translateY(0);
            opacity: 1;
        }
    }
`;

const NotificationAnimationDiv = styled.div`
    max-width: 480px;
    position: relative;
    z-index: 3000;
    animation: slide-in-from-top 0.5s cubic-bezier(0.24, 0.48, 0.47, 0.95);
    overflow: hidden;
    ${SlideInAnimation}	
    visibility: ${props => props.fadeOut ? "hidden" : "visible"};
    opacity: ${props => props.fadeOut ? 0 : 1};
    transition: ${props => props.fadeOut ? "visibility 0.5s linear, opacity 0.5s linear, max-height 1s 0.5s ease-out, margin-bottom 1s 0.5s" : "none"};
    max-height: ${props => props.fadeOut ? "0px" : "100%"};
    margin-bottom: ${props => props.fadeOut ? "0px" : "12px"};
`;

export default function NotificationAnimation({ children, id, removeNotification }) {
    const [isClosing, setIsClosing] = useState(false);
    const [isClosed, setIsClosed] = useState(false);

    const sleep = (ms) => {
        return new Promise(resolve => setTimeout(resolve, ms));
    }

    useEffect(async () => {
        await sleep(currency.notificationDurationShort * 1000);
        setIsClosing(true);
    }, []);

    useEffect(async () => {
        if (isClosing) {
            await sleep(2000);
            setIsClosed(true);
        }
    }, [isClosing])

    if (isClosed) {
        removeNotification(id);
        return null;
    }

    return (
        <NotificationAnimationDiv fadeOut={isClosing}>
            {children}
        </NotificationAnimationDiv>
    )
}